default_install_hook_types: [pre-commit, pre-push]
default_stages: [commit, push]

repos:
- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black"]

- repo: https://github.com/ambv/black
  rev: 23.7.0
  hooks:
  - id: black
    language_version: python3
    args: ["--line-length", "88"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: no-commit-to-branch
    args: [--branch, main]
  - id: check-merge-conflict
  - id: check-ast
  - id: check-builtin-literals
  - id: check-yaml
  - id: check-json
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys]
  - id: check-added-large-files
  - id: debug-statements

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      additional_dependencies: [
            "flake8-docstrings",
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-docstrings",
            "flake8-pyproject",
      ]
